[sources.source_syslog]
type = "syslog"
address = "0.0.0.0:1514"
max_length = 102_400
mode = "udp"
path = "/tmp/syslog_udp"

[sinks.sink_loki]
type = "loki"
inputs = [ "source_syslog" ]
endpoint = "http://127.0.0.1:3100"
labels.datasource = "source_syslog"
out_of_order_action = "rewrite_timestamp"
encoding.codec = "json"